CREATE VIEW MalfunctioningRoutes AS
SELECT DISTINCT
    r.ROUTE_ID,
    r.NAME,
    ie.SELECTOR AS MALFUNCTION_TYPE
FROM
    ROUTE r
JOIN
    ROUTE_STRETCH rs ON r.ROUTE_ID = rs.ROUTE_ID
JOIN
    STRETCH s ON rs.STRETCH_ID = s.STRETCH_ID
LEFT JOIN
    INFRASTRUCTURE_ELEMENT ie ON s.STRETCH_ID = ie.STRETCH_FK
WHERE
    ie.STATUS = 'B';